module.exports = {
  websiteModel: [
    {
      websiteName: "bestdeals.today",
      websiteLink: `https://au.bestdeals.today/`,
      productDetails: 'div[class="deal__main-wrap"]',
      linkTag:
        "ver_container clickout product_box_link deal__container deal__container--ab-two-col rf_js_redirect-link",
      imageTag: "img",
      priceTag: "deal__old-price deal__old-price--ab-two-col",
      titleTag: "deal__title-ch deal__title-ch--ab-two-col",
      suffix: "",
    },
    {
      websiteName: "amazon-au",
      websiteLink: `https://www.amazon.com.au/s?k=`,
      productDetails: 'div[class="a-section a-spacing-medium"]',
      linkTag: "a-link-normal s-no-outline",
      imageTag: "img",
      priceTag: "a-offscreen",
      titleTag: "a-link-normal a-text-normal",
      suffix: "",
    },
    {
      websiteName: "bigw",
      websiteLink: "https://www.bigw.com.au/search?text=",
      productDetails: 'div[class="ProductTile"]',
      linkTag: "product-image",
      imageTag: "img",
      priceTag: "dollars",
      titleTag: "product-name",
      suffix: "",
    },
    {
      websiteName: "jbhifi",
      websiteLink: "https://www.jbhifi.com.au/?query=",
      productDetails: 'div[class="ais-hits--item ais-hits--item"]',
      linkTag: "ais-details-a product-tile",
      imageTag: "img",
      priceTag: "ais-hit--price price",
      titleTag: "ais-hit--title product-tile__title",
      suffix: "",
    },
    {
      websiteName: "kogan",
      websiteLink: "https://www.kogan.com/au/shop/category/",
      productDetails: 'div[class="_1umis"]',
      linkTag: "_3w8sH",
      imageTag: "img",
      priceTag: "_2AQgf",
      titleTag: "_1A_Xq",
      suffix: "",
    },
    {
      websiteName: "woolworths",
      websiteLink:
        "https://www.woolworths.com.au/shop/search/products?searchTerm=",
      productDetails:
        'div[class="ng-tns-c327-9 product-grid--tile ng-star-inserted"]',
      linkTag: "shelfProductTile-imageWrapper",
      imageTag: "img",
      priceTag: "price price--large ng-star-inserted",
      titleTag: "shelfProductTile-descriptionLink",
      suffix: "",
    },
    {
      websiteName: "banggood",
      websiteLink: "https://www.banggood.com/search/",
      productDetails: 'div[class="p-wrap"]',
      linkTag: "exclick jsObserver",
      imageTag: "img",
      priceTag: "price notranslate",
      titleTag: "title exclick jsObserver",
      suffix: ".html?from=nav",
    },
  ],
};
